mixed-port: 7890
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: debug
ipv6: true
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 114.114.114.114

proxies:
  - name: Seattle
    type: hysteria2
    server: 104.168.22.226
    port: 37832
    password: baf74b30
    sni: www.bing.com
    skip-cert-verify: true
  - name: 🇯🇵日本
    type: trojan
    server: automq3-proxy.automq-sg.com
    port: 443
    network: tcp
    tls: false
    password: dQUWbcwECl
    skip-cert-verify: false
    ip-version: dual
  - name: 🇸🇬新加坡
    type: trojan
    server: automq4-proxy.automq-sg.com
    port: 443
    network: tcp
    tls: false
    password: dQUWbcwECl
    skip-cert-verify: false
    ip-version: dual
  - name: lapink原生ip
    type: vless
    server: tw-ty-line1-2-2.sudatech.store
    port: 21082
    uuid: e7adaa99-8363-3ec4-b849-307c99005405
    network: tcp
    tls: true
    servername: learn.microsoft.com
    flow: xtls-rprx-vision
    skip-cert-verify: true
    client-fingerprint: random
    reality-opts:
      public-key: tf7ZDGaue4C43MM0ECIfjOS-0kk7XMSqfnaSY4Er5Fc
      short-id: 758719a6080f2767
    ip-version: dual
    udp: true
  - name: RN直连节点2
    type: hysteria2
    server: 107.172.99.78
    port: 43224
    tls: false
    password: b6ffadff-b7ad-497e-87c4-a2b315db85ea
    alpn:
      - h3
    skip-cert-verify: true
    fast-open: false
    ip-version: dual
  - name: HK家宽1
    type: hysteria2
    server: 118.141.151.139
    port: 33443
    tls: false
    password: a3c43273-ab4a-4d46-9974-228c0f96a9dc
    alpn:
      - h3
    skip-cert-verify: true
    fast-open: false
    ip-version: dual
  - name: MY节点1
    type: hysteria2
    server: 23.27.240.7
    port: 42421
    tls: false
    password: a999f41e-8d64-43ae-8447-c0212e064190
    alpn:
      - h3
    skip-cert-verify: true
    fast-open: false
    ip-version: dual
  

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - Seattle
      - 🇯🇵日本
      - 🇸🇬新加坡
      - lapink原生ip
      - RN直连节点2
      - HK家宽1
      - MY节点1

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: "https://ghp.ci/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - IP-CIDR,1.1.1.3/32,DIRECT
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN,services.googleapis.cn,PROXY
  - DOMAIN-SUFFIX,github.com,PROXY
  - DOMAIN-SUFFIX,linkedin.com,PROXY
  - DOMAIN-SUFFIX,renruihr.com,DIRECT
  - DOMAIN-SUFFIX,ustraveldocs.com,DIRECT
  - DOMAIN-SUFFIX,space-flight.org,DIRECT
  - DOMAIN-SUFFIX,xing.com,DIRECT
  - DOMAIN-SUFFIX,monster.com,DIRECT
  - DOMAIN-SUFFIX,stepstone.com,DIRECT
  - DOMAIN-SUFFIX,alipan.com,DIRECT
  - DOMAIN-SUFFIX,blog.csdn.net,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
